name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set .bashrc path
        shell: bash
        run: echo "BASHRC_PATH=$HOME/.bashrc" >> $GITHUB_ENV
      - name: echo .bashrc path
        shell: bash
        run: echo "$BASHRC_PATH"
      - uses: Erisa/write-file-action@master
        with:
          path: ${{ env.BASHRC_PATH }}
          contents: |
            echo "Hello World!"
          write-mode: append-newline
      - uses: actions/upload-artifact@v2
        with:
          name: profile
          path: ${{ env.BASHRC_PATH }}
