name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set .bashrc path
        shell: bash
        run: |
          echo -n "test
          test" > $HOME/file
          echo "FILE_PATH=$HOME/file" > $GITHUB_ENV
      - uses: Erisa/write-file-action@master
        with:
          path: ${{ env.FILE_PATH }}
          contents: |
            echo "Hello World!"
          write-mode: append-newline
      - uses: actions/upload-artifact@v2
        with:
          name: file
          path: ${{ env.FILE_PATH }}
